### ISSUE TITLE
Astral Plane: Last of the Norkos maps

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#11]
Information needed for Astral Plane map:

* Approximate size. Something large like Elemental Planes -3 (100x100), or smaller?
* What should go there? Trainers, bosses, collectibles, structures, treasure, additional decor? There isn't much in the way of astral themed decor.
* How do you get out? A portal back to elemental planes -3 makes sense, as you have to teleport from there with the astral crystal collectible so it can be like an open doorway once you can reach it.
* Possible to use the astronomical entity sprite as a background? It would be in unreachable locations, so maybe just set to blocking? Or would you rather I not do that?

My ideas:
* Have some buildings there, and use fences to make yards. Almost like the inhabitants of the astral plane have gardens where they have regular trees and grass in small spaces.
* Magically enhanced regular item collectibles. My background with the astral plane is from D&D, where it's a place between worlds where magic is stronger. So maybe a few 'lost' items that have been around and are now magical by being here. magic cup, planar poodle, etc.'
* It will be floating islands in a night sky background, so I think a few temple like structures on the islands with teleports to the other floating islands. (pillars, pillars everywhere)

**Comment by seiyria** [comment]
* I think 100x100 is more than enough.
* No trainers, one boss (I have no idea what to call it yet, maybe The Corruptor), definitely a bunch of buff spaces like the finditem and whatever tiles, some buildings
* Get out the same way you came in, there is a portal
* I think the astroent is fine if you throw it off in the distance, periodically, but we have the night sky and the purple thing to use as a background where necessary. Hell, if you wanted to set it to blocking and use it as a wall in some places, that'd be fine too, I think.

Here's what I'm thinking, and I'm thinking we're thinking the same thing. I'm imagining a surreal town floating in the void. Like a town that lives on the water, except instead it's on the void. So, a perfectly reasonable town (maybe a ghost town?) that's outside the boundaries of space and time. I think it should mish-mash the elements a bit, too, so there can be acid splashes, and water, and trees, and desert. It doesn't have to be super coherent. 

Collectibles: I think warped and twisted things make sense as well as what you said - magic cup, planar poodle (love the alliteration), maybe also a melted clock, void crystal, an incorporeal orb, and for some reason I think a (twisted) turnip would be great, too.

Definitely a fan of your idea of teleporting between islands. Not all of them have to be teleports, I think, but definitely make use of them. Since you can make use of custom travel text, I think you could also use stairs and ropes (not going up or down, just between islands) to make something really interesting.

**Comment by sedgwick** [comment]
Great idea with the customText. "A crystal clear staircase appears before %playerName. They walk across to %destinationName." I was thinking maybe one of the large islands has a narrow landbridge that connects to another large piece of land. and at 100x100, there will be plenty of space.

Also, a path that goes right off the edge of an island, but a distant island has that same path pick up, like they were connected before but split.

**Comment by seiyria** [comment]
I like it. Sounds good.

**Comment by sedgwick** [comment]
http://puu.sh/qEBQ0/95224c039e.png

Making progress posts for this one, since this isn't a single day map. Astral hub, connects to elemental planes -3, requires astral crystal on both sides. planar poodle is by the little rest area for those who just arrived. made mention of Astral Alliance, maybe the kind of norkos council of this plane. since there will be inhabitants on the other islands (at least 4 more islands) they would have some kind of group.

**Comment by sedgwick** [comment]
Also altered the astral peak on elemental -3, both sides have the same set up of columns (because rituals).

http://puu.sh/qEC2d/daa7287a36.png

**Comment by seiyria** [comment]
So far, this looks really nice!

**Comment by sedgwick** [comment]
Island 2 has the Magical Birdbath collectible, because the idea of a player making it all this way for a big birdbath is great (and you also find it in one of the walled in earth like gardens). A few houses and a merchant near the peak that leads to a third island to make later. Has a way back to the hub in the SE corner. Will do flavorText later for all the different ways they get around the islands.

You said no trainers, but how about a sandwich artist? You said it yourself, everyone needs to eat. Would put on a later island, or in one of the 2x1 rooms on this island, I don't know yet.

http://puu.sh/qG1Ja/271a354308.png

**Comment by seiyria** [comment]
liking it so far! it's definitely giving off that surrealist vibe that I was going for. I think a small island with a sandwich artist would actually be hilarious, so lets do it.

I'll probably add an acheivement for every set of things and have it calculated automatically, so if you line up the lore, I'll make it work. maybe have a sandwich artist collectible here, too, and it can unlock an astral sandwich skill for them too.

**Comment by sedgwick** [comment]
http://puu.sh/qHcQU/c36492ff24.png

I put the regions up here this time to show that I'm adding a few more than usual. If you make it this far, it's nice to see a lot going on. 2 new collectibles, the Twisted Turnip and Incorporeal Orb.  Made the zone in NE corner for future unfinished boss. That's not as important since battles are still WIP. NE Island has the Astral Boardwalk, NW has the Old Astral Fortress and farther west is the fungal forest.

Boardwalk connects back to hub as well as the ruins of the sandwich shop. that NE island was shaken up by whatever the boss will be up there. I think I'll add a little more floating ruins later.

**Comment by seiyria** [comment]
Looks good! The only thing off the top of my head, I'd add a region for astral boardwalk. Loving the shakenness of the NE area. I like how the NW is turning out as well, it's certainly something interesting!

**Comment by sedgwick** [comment]
I did add one for the sandwich artist right after, I called it the One Stop Sandwich Shop of the Stars.

**Comment by seiyria** [comment]
Ah, sorry. I forgot exactly what a boardwalk is. I was referring to the bridge but that struck me now as "doh, that's a bridge"

**Comment by sedgwick** [comment]
I called the bridge the great astral span. My idea is they tried to expand west but were faced with resistance from the fungal forest. So the ruins of the fortress are being overgrown.

**Comment by seiyria** [comment]
Yeah, that sounds okay. It is pretty nutty in the astral realm, where things make even less sense than everywhere else.

**Comment by sedgwick** [comment]
http://puu.sh/qI47G/00f1243ed5.png

Still a lot to do, but I could consider this a complete map of the islands. That said, if you want me to fill in anymore of the void with additional islands, I'd be happy to do so if you see a spot you think one should go.

Teleports need done, and I still have a few decorative things to do around the map. Presently, the only way back is to elemental plane -3 at the astral hub. I did, however, make _The Astral Path_, a ship that is heading to Cabran. SW Island is the void vactories and has the melted clock. E island has the void crystal and is wilderness at the moment, unless you had a name idea for that island. In addition, I really thought a sandwichartist collectible that's rare or legendary would be fun at the One Stop Sandwich Shop of the Stars, but haven't come up with one yet. Any ideas?

**Comment by seiyria** [comment]
It looks nice! Spaced out decently well, so there isn't a need for more
islands, I think. For a collectible, I think we can just call it an Astral
sandwich.

**Comment by sedgwick** [comment]
http://puu.sh/qLO8T/7b63a6ed31.png 

#23 submitted, astral plane is complete (for now, Cabran will include an update to planes teleport in the future).
