### ISSUE TITLE
Teleport Tile Bugs

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#15]
Certain stairs and teleport tiles load the wrong sprite, or don't seem to load at all.

Mythos -2: http://puu.sh/q7q47/e2e6f9932d.png
Mythos -1: http://puu.sh/q7oFY/d225bcb6f4.png

Also, the stairs that look like pirates, when you hover over them, showed the relevant teleport info. The teleport tiles that are not showing on mythos -2 do not display anything at all when hovering over them.

Only noticed on these two maps, will make a note if I see anymore.

**Comment by sedgwick** [comment]
Replacing the object in Tiled with the same information seems to have fixed this issue.

**Comment by seiyria** [comment]
Awesome. Still not sure why it happened to begin with, but I'm glad it was solved.
