### ISSUE TITLE
Splendid Dragon Keyring has no flavor text

### ISSUE THREAD

**Issue by boozledorf** [IdleLands/Maps#161]

**Comment by sedgwick** [comment]
https://github.com/IdleLands/Maps/blob/master/content/boss.json#L1419

Not sure why it isn't showing up since there is a set flavorText. It appears with no flavorText in Boozle's global page as well.

**Comment by seiyria** [comment]
Hm. It's possible in this case that boss collectibles aren't being created properly. Please follow up and let me know if, after a reboot, you still don't have any flavor text on the collectible. That will help me pin down where this is happening.

**Comment by boozledorf** [comment]
Update: I have since gotten another collectible, Bottle of Ketchup.  Now, Splendid Dragon Keyring is displaying its flavor text, but Bottle of Ketchup is not.

**Comment by seiyria** [comment]
Probably so. Collectibles are never updated otherwise. I'll move this to idlelands proper. Thanks for following up!
