### ISSUE TITLE
Mythos -3 Gold Farm Spot

### ISSUE THREAD

**Issue by JukeDragh** [IdleLands/Maps#164]
The room with the Dragon King is very easy to sit in and farm. Unlike the Merchant guild ascension areas, there isn't any teleports to help reduce chances of big gains.

**Comment by JukeDragh** [comment]
I might say that I can get over 20mil per hour in there with seeker on

**Comment by sedgwick** [comment]
#169 should reduce the ease of farming in the King's throne room, while reducing the high gains.
