### ISSUE TITLE
Change requireX doors/stairs to use jail door sprites

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#170]
A while ago someone (Sorry, I forget who) had the idea to use the jail style doors as identifiers for locked doors, that is, the doors that have a requireX on them. At first I was against it since I liked using them for the visual, but after standardizing all the teleports by color I think that being able to look at the map and identify requireX doors 'at a glance' is more important than a jail door being used decoratively for the few jail cell areas across the world.

@seiyria mentioned creating a script that would identify all doors that have a requireX on them, which will aid in the process when I go through and make the change.

After this change goes into effect, the player will easily be able to scan the map and see that a door has a requirement on it, since I know I've seen a few people get tripped up at those unique locations (especially the Necronomicon collectible).

**Comment by seiyria** [comment]
https://travis-ci.org/IdleLands/Maps#L432

**Comment by sedgwick** [comment]
Check to see if it is possible to add the map for each of the requireX objects.

**Comment by seiyria** [comment]
Should work better now!

**Comment by sedgwick** [comment]
Same idea for requireX ascend/descend. Use the regular stairs for unlocked stairs, and the ladder up/down as a requireX ascend/descend. https://puu.sh/vYjl5/31b0dc1b83.png
