### ISSUE TITLE
Collectible Rarity Update

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#22]
Go through all current collectibles and assign higher rarity when needed. Pro for hard to reach ones, Godly for very hard to reach ones as well as very important items.

@seiyria, Collectibles currently only use those two rarities. Is there an Idle rarity like equipment has? If so, should it work up in difficulty and have pro, then idle, then godly collectibles?

**Comment by seiyria** [comment]
There are also `guardian` collectibles, for those that drop from bosses. The rarities are the same as equipment, even if they're not used as such. I think idle collectibles should be reserved for hard to reach ones (ie, lets redo the kings key to that), and reserve godly for things in the deepest and hardest to reach places (norkos -11, astral plane, etc). 

Now that I think about it, though, some collectibles unlock skills. I think some specific rarity should be reserved for that, and I'm thinking it's `pro`. In fact, I'm not sure what `idle` rarity collectibles should be in that case. Maybe:

* most collectibles are `basic`
* skill-unlocking collectibles are `pro`
* important and somewhat tough to reach collectibles (like the kings key) are `idle`
* very tough to reach collectibles (n-11, etc) are `godly`

thoughts?

**Comment by sedgwick** [comment]
Sounds great. And thanks for the information on guardian collectibles, I didn't know about that category. Though, It'll make it a little trick because I'll have to check each one now against skills. Do you know what the best way to do that would be, or which file(s) to check?

**Comment by seiyria** [comment]
You can use [this search](https://github.com/IdleLands/IdleLandsOld/search?utf8=%E2%9C%93&q=collectibles%3A) and only do it for collectibles that are attached to skills.

**Comment by seiyria** [comment]
When we do this, I'd like to attach more collectibles to powerful versions of skills. I'll probably be implementing each skill (though some of their effects may change), and I'll be implementing more tiers of each skill as well. You can see the list of collectibles here: https://travis-ci.org/IdleLands/Maps#L172 (you have to expand it).

I'm not suggesting we should do one collectible for every skill, but some skills definitely deserve an "ultimate" form. If you can see any existing collectibles (or want to make new ones) that would go well for a particular skill in old idlelands, let me know as well, since that will affect the new rarity.

**Comment by seiyria** [comment]
Maybe `idle` collectibles could be ones that unlock pets.

**Comment by sedgwick** [comment]
Unlocking a feature takes precedence over how it was earned. so basic for most, pro for skills/ult. skills, idle for pets, godly for other important collectibles, guardian for boss ones. however, if a boss drops a collectible that unlocks something, it will be idle/pro not guardian.

Guardian collectibles that need to be pro/idle need to be overridden using the "rarity" property.

**Comment by sedgwick** [comment]
#25 updates some of these. Still need to:
* Update any basic collectibles to godly if they are important or extremely difficult to reach (but not pro/idle). I can cover the difficult to reach part but are there any important lore collectibles that should be updated? https://travis-ci.org/IdleLands/Maps#L172 Another note, with the importance of rarity coming, it would be nice if this list was able to display rarity.
* Attach/Create collectibles for high ranking skills.  From Sei: "I think all of the new spells that have a tier >lv 100 are worthy of having a collectible attached"

Here are the spells that currently have a collectible requirement that were added in #25. Not all of these are in game yet, according to the docs.

* Summon dracolich requires Undead Dragon Scale
* Summon demogorgon requires Gorgon Snake
* Bonecraft requires Necronomicon
* Cure requires Cleric's Text
* Lights From the Stars requires Ancient Lute
* Sweeping Generalization requires Generalist's Guidebook
* Double Tap requires Fighter's Manual
* Energy Missile requires Mage's Tome
* Deathtouch requires Forbidden Cleric's Text

**Comment by seiyria** [comment]
we can worry about lore-important ones later, I can't think of many now, besides the ones that get you going like the crystals and the key.

All of the necro skills are not added yet, but I did not know light from the stars requires the ancient lute. I might make that the chant of obliteration requirement instead (lets make a note of that, and I'll do them all at once).

Hopefully I'll have all the skills done by the end of the week, so we could get this all taken care of in one sweep.

**Comment by sedgwick** [comment]
Proposed collectibles for Archer, Bard, Bitomancer, Cleric, and Fighter. More coming later.

* Archer's AntiMagicArrow 3 requires Ivory Arrow from Funhouse -2.
* Bard's LitanyOfPain 3 requires ancient lute (as you mentioned previously) from Bard Island -1.
* Bard's LightFromTheStars 1 requires Soaked Sitar from Bard Island -1.
* Bitomancer's Byte 6 requires Giant Sized Flask from Leviathan Mountain (Giant's Tower).
* Bitomancer's ZeroDay 3 requires Vial of Liquid Fate from Fate Pools -1.
* Bitomancer's DoS 3 requires Gauntlet from Norkos Dungeon -9.
* Can't find a good one for Bit 6, one option is Strange Helm on Norkos Dungeon -2, but that's pretty easy to get.
* Cleric's CureGroup 4 requires Golden Artifact from Idle Island.
* Cleric's Cure 4 requires Strand of Fate from Fate Pools -2.
* Fighter only has attack 3 at the moment at 100, but the two free collectibles don't seem like a good fit. Mini shuriken seems like it should be for some other kind of ability or just basic rarity, and broken katana seems like a terrible thing to use for your super strong attack, but logic is pretty flexible in IdleLands so I can just pick one of those if you want.

Additional changes as a note to myself:
Odd Amulet unlocks an area, needs to be godly.

**Comment by seiyria** [comment]
I'm ok with all of these. Jar of Magic Dust is fine for mage as well as gen, broken katana is fine for fighter. I'll use the unpleasant glass of water as well.

**Comment by sedgwick** [comment]
All in game skills that needed collectibles have been added, so new ones can be selected at creation. This will be much easier with the improved collectible list too!
