### ISSUE TITLE
Add new regions

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#29]
The territorial title is currently impossible to get, with 92 regions in game. Many maps have unique locations that could have new regions, and would make many of the norkos stair events provide more info since they'll pick the region name over the map name if there is one (I believe that's how it works anyways).

**Comment by seiyria** [comment]
I don't think they use the region name, you have to specify a `formalName` in the teleport tile.

**Comment by sedgwick** [comment]
#30 adds 24 regions. There are still some places that could potentially be new regions, but now that territorial title is possible I feel this is good for now.
