### ISSUE TITLE
Donators and Contributors

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#37]
For @seiyria to copy/paste information related to those who donated to the game or contributed in some way. If you are one of those people and found yourself here, then here are a few things you can do to help us leave your mark on the game.

You can select one of these sprites to display in game: [Link](http://i.imgur.com/FaHvgvF.png)

(Optional) You can leave a short quote that will be visible from the map tab when any player is on the map "Hall of Heroes" which is accessible from Norkos Town. @seiyria approves all quotes before they appear in game. If you would prefer not to have a personal statue, then that's all right too!

**Comment by seiyria** [comment]
Pending:

* Yngvildr
* OnionKnight (need quote - sprite=Pirate)

**Comment by sedgwick** [comment]
Only one now pending is Robert, Cerleen has been added with #48.

**Comment by seiyria** [comment]
Clair: E7, I want to get off Mr. Seiyria's wild ride

**Comment by AscendedGravity** [comment]
Clair added with https://github.com/IdleLands/Maps/pull/76

**Comment by seiyria** [comment]
Need to add an anonymous statue.

**Comment by seiyria** [comment]
XazR: D3, no quote at this time

**Comment by seiyria** [comment]
our boy cerleen has a quote! "If you enjoy doing nothing this game is a hell lot of fun"

**Comment by seiyria** [comment]
Jorgen Von Strangle - quote and sprite tbd

**Comment by seiyria** [comment]
Kold - D1 - The best time to wear a striped sweater is all the time.

**Comment by AscendedGravity** [comment]
Kold added with https://github.com/IdleLands/Maps/pull/80

**Comment by seiyria** [comment]
PursuantAunt - E5 - Quote: hoping to get the things

**Comment by seiyria** [comment]
Character Name: Bodo Sprite: A6 Message: Nice butt. Not very smart.

**Comment by seiyria** [comment]
anon statue

**Comment by seiyria** [comment]
deaditslife - E3 - quote tbd

**Comment by seiyria** [comment]
Kain, B1, 	«IdleLands» found a gold ingot with a lemon peel wrapped around it, and it was worth 2 gold! [+2 USD]

**Comment by seiyria** [comment]
Nas, 	Sprite: C-6 Quote: Habits begin as cobwebs and end up as chains.

**Comment by seiyria** [comment]
Xiezhi - (F6) with the quote "When I start my new job my power level will be over 9000!"

**Comment by seiyria** [comment]
Plutia, A5, no quote yet

**Comment by seiyria** [comment]
Spely, no sprite/quote

**Comment by seiyria** [comment]
Juicy, 6A

**Comment by seiyria** [comment]
Kalvarus, C3, "Always have FUN!"

**Comment by seiyria** [comment]
DiCE1904, A-6

**Comment by seiyria** [comment]
Irwin, B6, "Don't let your dreams be dreams."

**Comment by seiyria** [comment]
Simplicity, 6A

**Comment by seiyria** [comment]
Marmar, A5

**Comment by seiyria** [comment]
Fish, TBD

**Comment by seiyria** [comment]
Azure, C-6, What is this 'money' you speak'th off?

**Comment by seiyria** [comment]
Firesale, B3 "The fire rises, come buy some!"

**Comment by seiyria** [comment]
Blackheart, no sprite/quote

**Comment by seiyria** [comment]
Lets just add the above 3 for now as ? marks.

**Comment by seiyria** [comment]
Gex87, C4, "For the Emperor"
for this one can you also please give him the donator achievement, sedg? thanks in advance!

**Comment by sedgwick** [comment]
HoH complete, still need to issue the donator achievement next time I see Gex87 online.

**Comment by seiyria** [comment]
Tonka, quote/sprite tbd (for now just question mark is fine)

**Comment by seiyria** [comment]
baram, E7, "smooth."

**Comment by seiyria** [comment]
Lucker

**Comment by seiyria** [comment]
Krondor, B2,  "Gotta get them all!"

**Comment by seiyria** [comment]
JuliusSeizure

**Comment by seiyria** [comment]
Nophie

**Comment by seiyria** [comment]
xSkazix, "Every little helps"

**Comment by seiyria** [comment]
McCloude, 	B5 / Semper Fi

**Comment by seiyria** [comment]
EvoGeek, G2, "I have no idea what I'm doing"

**Comment by seiyria** [comment]
Hemlock = Sprite - A6 Quote - "In the most Dire circumstances, in the most Grizzly of times, even when the world seems to be your Polar opposite, just remember to keep the Bear necessities close to your heart"

**Comment by seiyria** [comment]
Seli Taiken, c4, no quote

**Comment by seiyria** [comment]
Palion

**Comment by seiyria** [comment]
xFlyingMurloc: Keep Moving Forward - Anyfin can happen!

**Comment by seiyria** [comment]
Aeternalis: Sprite: C3 Quote: Luna nos custodiunt

**Comment by seiyria** [comment]
Guts, C5

**Comment by seiyria** [comment]
Aviatros, D4 Custom Text: Am Anfang war das Nichts und dann: Peng - KEKSE!!

**Comment by seiyria** [comment]
xrebo

**Comment by seiyria** [comment]
TekNo,  A7 "Just do it, tomorrow"

**Comment by seiyria** [comment]
Clippy, Sprite B3, text "I like shorts! They're comfy and easy to wear!"

**Comment by seiyria** [comment]
Loto

**Comment by seiyria** [comment]
Dad, the Flower Sprite -"Just don't let this game distract you from the fact that in 1998 The Undertaker threw Mankind off Hell In A Cell, and plummeted 16ft through an announcers table."

**Comment by seiyria** [comment]
commiehunter - B6 sprite custom text: free helicopter rides!

**Comment by seiyria** [comment]
Raka

**Comment by seiyria** [comment]
Magashisama, 6b.

**Comment by seiyria** [comment]
Katya

**Comment by seiyria** [comment]
Tongle

**Comment by seiyria** [comment]
Rallio

**Comment by seiyria** [comment]
Aurilliux

**Comment by seiyria** [comment]
Kender,	E7 "«seiyria» made 10 gold developing a sweet game. Good job. [+10 gold] Cheap-ass «Kender»."

**Comment by seiyria** [comment]
C7 Text: Rampage! Username: Boltonsquad

**Comment by seiyria** [comment]
mars  Any Sprite you want to add me ;) custom text: :Aliens:

**Comment by seiyria** [comment]
pkwtf

**Comment by seiyria** [comment]
Moaxey

**Comment by seiyria** [comment]
HashtagHermit, C6

**Comment by seiyria** [comment]
huntpixel

**Comment by seiyria** [comment]
Arimidex, :3

**Comment by seiyria** [comment]
Aeref

**Comment by seiyria** [comment]
Buffalax, B2 Quote: "EIGHTY THOUSAND DOLLARS!"

**Comment by seiyria** [comment]
MrRabbit 	Sprite: C3 Quote: "Keep calm and Hop on"

**Comment by seiyria** [comment]
Searlas

**Comment by seiyria** [comment]
Funeral	Sprite = C6 Quote = "Do not be trapped by the need to achieve anything. This way, you achieve everything"

**Comment by seiyria** [comment]
Glopii, 	Sprite A6, no message. Thanks!

**Comment by seiyria** [comment]
Maxxy

**Comment by seiyria** [comment]
fusd

**Comment by seiyria** [comment]
Dan Rowan, B2 Thanks for the awesome game!

**Comment by seiyria** [comment]
Roberto, Sprite: D5 Text: Labor lusum meliorat

**Comment by seiyria** [comment]
JJx

**Comment by seiyria** [comment]
Vasyan, 	D3/Hello

**Comment by seiyria** [comment]
GeneralFrontal, G1

**Comment by seiyria** [comment]
Khezgaan, 	Sprite :B7 Text: "Never compromise. Not even in the face of Armageddon."

**Comment by seiyria** [comment]
Masterojack, C1

**Comment by seiyria** [comment]
Dzik, C5 It all started with being player 2 in duckhunt.

**Comment by seiyria** [comment]
Sviseerd

**Comment by seiyria** [comment]
Stuwolf, B5 Sprite, and my Quote is " I see, i go, i Idle !"

**Comment by seiyria** [comment]
Tano

**Comment by seiyria** [comment]
anonymous, "Without love, it cannot be seen."

**Comment by seiyria** [comment]
Yuju

**Comment by seiyria** [comment]
Anonymous

**Comment by seiyria** [comment]
MikakoTabe

**Comment by seiyria** [comment]
Zim, 	Sprite: B6. Message: Thanks for the amazing game!

**Comment by seiyria** [comment]
Stanne

**Comment by seiyria** [comment]
LouisPanda

**Comment by seiyria** [comment]
KaizuVN, 6-B, Good game !

**Comment by seiyria** [comment]
Aesthetics, E2

**Comment by seiyria** [comment]
Farflier, A6, It's dangerous to go alone! Take this.

**Comment by seiyria** [comment]
Santos L Halperr, A1, "I'm helping!"

**Comment by seiyria** [comment]
one anonymous statue

**Comment by seiyria** [comment]
one anon statue

**Comment by seiyria** [comment]
Koinkoin, E7, 'Koin ?'

**Comment by seiyria** [comment]
Optimal

**Comment by seiyria** [comment]
Kong

**Comment by seiyria** [comment]
jays, B6

**Comment by seiyria** [comment]
Sprite B6 "I aim to misbehave"

**Comment by seiyria** [comment]
suor minchiona
C1 "It always does seem to me that I am doing more work than I should do. It is not that I object to the work, mind you; I like work: it fascinates me. I can sit and look at it for hours. I love to keep it by me: the idea of getting rid of it nearly breaks my heart."

**Comment by seiyria** [comment]
Undigested
F5 Palm Tree - Quote "Join the kitten pile!"

**Comment by seiyria** [comment]
Groshurn
Boss Monster "Lurker Extreme @ Work ;)"

**Comment by seiyria** [comment]
Derpinatrix

**Comment by seiyria** [comment]
TheAllKing, C2, no text

**Comment by seiyria** [comment]
Nagun

**Comment by seiyria** [comment]
Yellow, A-5, this is for those poor souls who cant drink yet.

**Comment by seiyria** [comment]
BluR, B5 Custom text "henlo"

**Comment by seiyria** [comment]
Artidrius

**Comment by seiyria** [comment]
Martin Unbelievably, C-1

**Comment by seiyria** [comment]
Schizophoenix

**Comment by seiyria** [comment]
DeepLake
Chosen sprite: A7 Message: Wings of Freedom

**Comment by seiyria** [comment]
Feenux, E5 (no quote)

**Comment by seiyria** [comment]
Mhallice

**Comment by seiyria** [comment]
steph101, anonymous, no quote

**Comment by seiyria** [comment]
Inusion, 

D1 - "LGBT in the house!"

**Comment by seiyria** [comment]
BubbaSWalter

**Comment by seiyria** [comment]
MoleOfWar

**Comment by seiyria** [comment]
Cinnamon Haske, not a bear "All you need to do to succeed is try."

**Comment by seiyria** [comment]
VolkFrost, D4, ayy lmao

**Comment by seiyria** [comment]
Shunamaji, D7

**Comment by seiyria** [comment]
PlutoniumApe, c6 "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn"

**Comment by seiyria** [comment]
Sprite "A6" I can't think of a quote. Feel free to just use this.

**Comment by seiyria** [comment]
Sprite - C1 Text - MMFWCL

**Comment by seiyria** [comment]
Kisaki

**Comment by seiyria** [comment]
DiCE1904, B6 "Thanks!"

**Comment by seiyria** [comment]
MrIconic, A4 -> "Creating games while my character creates himself? Sounds good to me."

**Comment by seiyria** [comment]
flexlolz

**Comment by sedgwick** [comment]
Hall of Heroes - Complete. https://github.com/IdleLands/Maps/pull/257
:)
