### ISSUE TITLE
Current Map Revisions

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#4]
With the maneuverability issues corrected as best as we can for now, using the new sprites for the current maps will be a priority above making new ones. Here are a list of the many general updates for all maps, and a few specifics I can think of.

* ✔ More of the general decoration everywhere.
* ✔ Chamber of Ascension needs easier access to inner chambers.
* ✔ Work on Maeles Cave area.
* ✔ Remove all draygons, change to dragon.
* ✔ Guardian fragment collectible needs Lore.
* ✔ Re-do South East section of South Pole region.
* ✔ Check for improperly cased event names.
* ✔ Trainers that just got a sprite need swapped.
* ✔ Acid caves can finally be filled with acid.
* ✔ Region surrounding Minotaur Forest needs work.
* ✔ Vampire Lair should look a bit more dilapidated.
* ✔ ~~Vocalnus Town map clouds need color corrected. (The big bright square)~~ (edit: I figure now, after looking again, this can be used to note that the Gryffin Mountain is higher up than the rest of the terrain. However, I did clean up a couple extra grass tiles around Vocalnus Town.)
* ✔ Norkos Boathouse +1 stairs need correct name.
* ✔ Dark tower doesn't have to be bright brick anymore, with the addition of the stone door.
* ✔ Tombstone flavorText. Previously I used many skeletons for this purpose, but a tombstone adds another level of possibilities.
* ✔ Treasure tiles: I do not believe an issue is open for this, but in chat we discussed some treasure tiles, such as the bags and pile of gold, or merchants, all being able to force an event such as blessGold. Since these bags will have an actual mechanic, and not just decoration, it will be important to understand how they work before I put a between 1 or 30 in a room.
* ✔ Towncriers: the towncrier was previously used to announce messages that I believe anyone could post for a price, or was it only through guilds? I remember it being the main feature anyway. One in each town, so you have to be near one?
* ✔ Merchants: Easily they could be placed in buildings around the cities. Possibility of them moving around the map? I know moving NPCs would probably be a ways off, but just a thought for now.

**Comment by seiyria** [comment]
As for things that can be addressed:

* Treasure tiles - basically, if you add a forceEvent on a tile, it will trigger every time it's stepped on. It might not be a bad idea to add one to some boss rooms, maybe a few gold ones. The specific casing is important so if you set forceEvent it will have to be BlessGold or Merchant (those are the proper event names that this time)
* Altars, I'm not sure. We can see where we go.
* Town criers, basically people could pay to have advertisements run through the town crier. This will be coming back. One town crier per town region is probably a good metric.
* I won't have merchants wander the map yet. There definitely should be a static one in each town, and it should force the Merchant event.

**Comment by seiyria** [comment]
Small thing, but can we also open up the starter building a bit more? Maybe even remove the building, or something. It's rough when people get stuck in there and they've just started.

**Comment by sedgwick** [comment]
With #21 submitted, current map revisions are complete and any other changes can be made on a case by case basis.
