### ISSUE TITLE
Update teleports.json

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#44]
- Astral Town teleport has already been added, so step 1 is done.
- Add GM boss teleports for bosses that do not have one, make sure current teleports go directly to boss tile.
- Add GM trainer teleports for trainers that do not have one, make sure current teleports go directly to trainer tile.
- Organize the teleport list. Cities are already first, trainers, bosses.

Anything missing regarding a teleport update?

**Comment by seiyria** [comment]
nope. also, if you have any humorous locations you might want a teleport to (like hi 2 u) or any other interesting marks (BDK treasure hoard?) those can also be added. additionally, I wouldn't mind having one for the hall of heroes (probably drop it right in the center of the Olde area) so I can see and show people what's up.

**Comment by sedgwick** [comment]
https://github.com/IdleLands/IdleLands/issues/186

Waiting for teleport behavior to be updated to update.

**Comment by sedgwick** [comment]
Unique Location List:
* Hi 2 U
* BDK Treasure Hoard
* Merchant Vault L/R
* toLoc for Astral Town
* Update Jail Name to say it's a trap.
* Hall of Heroes
