### ISSUE TITLE
Boss items have properties that were removed from the game

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/Maps#46]
https://github.com/IdleLands/Maps/blob/master/content/bossitems.json

See also: IdleLands/IdleLands#104

**Comment by sedgwick** [comment]
Thanks for opening an issue on this. I was going to review the rest of the defunct properties in the maps repo. when I return next week (unless someone else does it before I return).

**Comment by sedgwick** [comment]
Thanks @Anexes for going through and updating maps and custom-assets!
