### ISSUE TITLE
merchant guild

### ISSUE THREAD

**Issue by seiyria** [IdleLands/Maps#52]
an idea:

have a merchant guild, a place that's got maybe like 100 merchants (ok that might be a lot) and is connected to every town. However, each entrance is blocked on each side, requiring a collectible from the respective town (meaning no cheese).

Maybe like a "Norkos Mechant Key" etc hidden in every town, or maybe not even in the town. Could be next to the town merchants, otherwise.

The idea is that people get a lot of options to buy things. Let the merchants shine bright.

**Comment by sedgwick** [comment]
Evil merchant's guild accessible from Evil Norkos. Doesn't connect with the other one, but on same map. Gives some love to Evil Norkos for those who manage to make it there.

**Comment by seiyria** [comment]
That sounds fun too. Evil Norkos really does need some love, eventually. Maybe the halloween event starts there... going to go note that.

**Comment by sedgwick** [comment]
Merchant Themed treasure set. Maybe low stats, but some nice gold bonuses and other properties that would make it something you might want to use, even if it puts you at a disadvantage combat wise. 

Planning on adding 6 merchants per town, and 8 in the center to put the merchant total at 50.

Also, here's a work in progress of the merchant's guild map. You can see how it's planned, with 6 large regions on either side for towns, a small section that won't connect for evil norkos, and a center area that, given you have the required things, will let you reach the others as a possible network of cities. That's all still in the works, more map work for now.

http://puu.sh/rg7xx/71433fc685.png

**Comment by seiyria** [comment]
Nice! That's interesting. Happy to see it.

**Comment by sedgwick** [comment]
Probably going to put a good amount of collectibles on bosses. Very few drop collectibles, and it would make it similar to a quest. Kill the Lizard King and have a chance at your collectible to the raburro merchant's guild as your reward.

**Comment by seiyria** [comment]
That sounds fantastic. Good use of boss collectibles.

**Comment by sedgwick** [comment]
Raburro section of the guild. I also added a way to access Norkos Town region and Raburro through the stairs, thought that would be fun. It'll have a requirement as well. Still trying to figure out what kind of theme I want to do for the inner section. It'll have a good amount of merchants too, so it will have stalls of some kind.

http://puu.sh/rg916/b0f2e11895.png

**Comment by sedgwick** [comment]
http://puu.sh/rgDT2/6a00ed55ff.png

**Comment by seiyria** [comment]
So many merchants. I am dazzled.

**Comment by sedgwick** [comment]
I also plan on adding two vaults of goldblesses that are inaccessible, for now. They will be so full of gold that i feel it couod be a requireAscension=1 kind of thing. And a high level boss.

**Comment by sedgwick** [comment]
#55 completes the Merchant's Guild. Details are listed in the PR.
