### ISSUE TITLE
Fate Lake

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#54]
*shiver*

Accessed from random parts of the world (dt-3, water plane, others). I currently see it as a grassy cave lake with 2x2 providence patches in the lake. Mushrooms, give it a real mythical cavern feeling. Good time for me to use the wood terrain a bit too.

**Comment by seiyria** [comment]
collectible name possibility: Tears of Past Adventures

I think, depending on the size of this place, I will add an achievement for it.

Also, what I'm thinking is to just make all the water an interactable, so we don't have to have those portals everywhere to signify the event. It should just be implied for water in this zone.

**Comment by sedgwick** [comment]
Complete with #66.
