### ISSUE TITLE
Some walls passable in the Merchant's Guild.

### ISSUE THREAD

**Issue by AscendedGravity** [IdleLands/Maps#63]
ATTN: @sedgwick 
Looking at the layers, seems to only affect "internal" walls, so there shouldn't be an issue of players accessing locked areas. But some walls in the Frigri as well as the eastern Raburro Hall (the one with the Homlet TP) can be passed through. Tested by Joe and Anexes.

**Comment by sedgwick** [comment]
Thanks for bringing it to my attention. Fixed with #64

**Comment by sedgwick** [comment]
The Eastern Hall is actually for Homlet town, not Raburro.

**Comment by AscendedGravity** [comment]
Ah, then Raburro is mentioned twice in the regions. See line 4153 of the json.
