### ISSUE TITLE
Chimera Dragon data looks off

### ISSUE THREAD

**Issue by Anexes** [IdleLands/Maps#69]
It *looks* like the first tier of every upgrade is the tier that the pet comes with when you buy it. All of the first tier upgrades have 0 cost, with one exception. [CD's first inventory upgrade](https://github.com/IdleLands/Maps/blob/master/content/pets.json#L402) (it only has one tier,) has a cost of 30,000. Not sure if there was supposed to be a second tier that cost 30,000 or if there's only supposed to be one tier and the 30,000 is just a mistake from porting the code or something, but it doesn't look intentional.

I don't think it's affecting anything, you just don't have to pay the 30,000 to get the upgrade because the CD comes with it. I only noticed because I was trying to format a table for my autodoc and it was the only tier 1 upgrade that had a non-zero cost. For all I know it's completely intentional, but I thought I'd make an issue just in case. If nothing else, it makes my autodoc a little more confusing to read :P

**Comment by seiyria** [comment]
Not intentional. Thought I got all of those. Want to submit a pr for that too?
