### ISSUE TITLE
Leaving Astral planes 

### ISSUE THREAD

**Issue by seiyria** [IdleLands/Maps#87]
Supposedly it requires a void Crystal but there is only an Astral crystal. 

If true, the validations need to be updated to account for this too.

**Comment by sedgwick** [comment]
The portal back to the elemental plane -3, as well as the portal to the astral plane, require the Astral Crystal. The Void Crystal is a collectible with no use, but we made mention of it before related to ascension or being changed in the future for other use.

http://puu.sh/smosP/25f86ec7a9.png

**Comment by seiyria** [comment]
Righto. Thanks!
