### ISSUE TITLE
class trainers in more places

### ISSUE THREAD

**Issue by seiyria** [IdleLands/Maps#9]
There should be more class trainers available in each town. I think each town should at least have the 4 core classes, since it's a choice now. Maybe also include sandwichartist in every town because we all need food, right?

The hidden trainers can probably stay hidden, though. Maybe each town has one class dedicated to them also, like frigri has the bitomancer.

**Comment by sedgwick** [comment]
Core class trainers are now in every town, except for Vocalnus Town and Homlet. There is now a SandwichArtist in every town. This will be sent with the PR for #4.
