### ISSUE TITLE
Tidying Up Norkos

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#96]
While I'm working on #1, I'll also be doing small fixes/changes to Norkos. Here's what I have found that still needs done, with more coming later as I find them.

* ~~Doppleganger boss added~~ (complete with #98)
* Astral Plane Boss added 
* Add flavorText townsfolk across Norkos, blue NPCs.
* Fix Frigri Funhouse sign (No longer need to be level 20 to enter) (Complete)

**Comment by seiyria** [comment]
I like the size, so lets keep it that way. I'm ok with expanding into a new map (astral dungeon probably makes more sense in this case). I think you can set the level higher but I don't know how effective it will be. Worst case, just scale the stats manually - level scaling for stats only does so much anyway. 

Not sure we need to require anything for the boss given how difficult it is to get there.

**Comment by sedgwick** [comment]
Astral Boss will have a trinket.

**Comment by sedgwick** [comment]
Possible BossParty idea for Astral boss:

Crystal Dwarf Commander and a set of henchmen. Since the Norkian Dwarves are virtually extinct (1 venerable dwarf boss remains, but is insane and holed up in the ruins), the Crystal Dwarves set about a centuries long journey through the astral plane in search of a portal to Norkos.

They found one near Astral Town, and crashed their [island-ship](http://puu.sh/tW8Jo/c140a2701f.png) into the region. They opened the Portal with the Astral Crystal, and created much of the corruption in other locations that we see on the map today.

Since these are dwarves _made_ of crystal, they will have a hefty amount of defensive abilities and be a level 200 party.

I think I'll take a little more time to plan this one, maybe see how I feel about this tomorrow. Think this is a plot worth pursuing?

**Comment by seiyria** [comment]
I like this. It's pretty not what I was expecting. Reminds me a bit of skyrim, where the dwarves went extinct but were probably the coolest things ever. That'll be these guys, except they're alive. They're also probably crazy.

**Comment by sedgwick** [comment]
I realize now though, there are plenty of dwarves in monster.txt in custom-assets. So even though they currently only show up in game in random battles or as 1 boss in 1 map, there are still dwarves around.

**Comment by seiyria** [comment]
They're not _crystal_ dwarves, though! :P

**Comment by sedgwick** [comment]
Fix teleport colors, look into possibly adding more.

**Comment by seiyria** [comment]
possibly for fate pool "teleports" they could just be turned into water, like fate lake

**Comment by sedgwick** [comment]
Barney in Evil Norkos (Acid Caves) needs flavorText.

**Comment by sedgwick** [comment]
https://github.com/IdleLands/Maps/blob/master/world-maps/world/Norkos.json#L3117

**Comment by sedgwick** [comment]
Fix Funhouse -1 and -2 stairs. They are still using the trapdoor sprite, which is for requireX stairs.

**Comment by sedgwick** [comment]
Astral plane map will get its own issue, otherwise this issue has been cleared up over the past year. Any new Norkos bugs/updates can have their own issue.
